### ISSUE TITLE
How to connect to localstack container with a custom image name?

### ISSUE THREAD

**Issue by baynezy** [localstack/localstack-desktop#9]
Since there is no way to `chmod` files on Windows I have created my own `Dockerfile` to circumvent this limitation.

```
FROM localstack/localstack:3.2

COPY --chown=localstack ./localstack-scripts/setup.sh /etc/localstack/init/ready.d/setup.sh

RUN chmod +x /etc/localstack/init/ready.d/setup.sh
```

I run this via `docker-compose`

```
version: '3.4'

services:
  document-db:
    image: mysql:8.0
    container_name: document-db
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "document-db"
      MYSQL_USER: "user"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  localstack:
    build:
      context: .
      dockerfile: ./localstack-scripts/LocalStack.Dockerfile
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-west-2
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range

```

This works as expected.

I intend to use the Desktop app to connect to this. However, I get the following error on start-up.

![image](https://github.com/localstack/localstack-desktop/assets/1049999/93c67869-6cba-471e-8049-44cf0450cf9f)

Are there any docs on how to configure this on Windows 10?

![image](https://github.com/localstack/localstack-desktop/assets/1049999/29cadb03-4f01-4cab-92d1-81ae6448479b)
